//
//  MoviesListInteractor.swift
//  MovieStoreCleanArchitecture
//
//  Created by Achraf Trabelsi on 9/27/18.
//  Copyright (c) 2018 Achraf TRABELSI. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesListBusinessLogic {
    func fetchMovies(request: MoviesList.Fetch.Request)
}

protocol MoviesListDataStore {
    var movies: [Movie]? { get }
}

class MoviesListInteractor: MoviesListBusinessLogic, MoviesListDataStore {
    
    var presenter: MoviesListPresentationLogic?
    var moviesWorker = MoviesWorker(moviesStore: MovieMemoryStore())
    
    var movies: [Movie]?
    
    
    // MARK: Fetch movies
    
    func fetchMovies(request: MoviesList.Fetch.Request) {
        moviesWorker.fetchMovies { (movies) in
            self.movies = movies
            let response = MoviesList.Fetch.Response(movies: movies)
            self.presenter?.presentFatechedMovies(response: response)
        }
    }
}
