//
//  MoviesListWorker.swift
//  MovieStoreCleanArchitecture
//
//  Created by Achraf Trabelsi on 9/27/18.
//  Copyright (c) 2018 Achraf TRABELSI. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MoviesListWorker
{
  func doSomeWork()
  {
  }
}
