//
//  MoviesListModels.swift
//  MovieStoreCleanArchitecture
//
//  Created by Achraf Trabelsi on 9/27/18.
//  Copyright (c) 2018 Achraf TRABELSI. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MoviesList {
    // MARK: Use cases
    
    enum Fetch {
        struct Request {
        }
        struct Response {
            var movies: [Movie]
        }
        struct ViewModel {
            struct DisplayedMovie {
                var title: String
                var details: String
            }
            var displayedMovies: [DisplayedMovie]
        }
    }
}
