//
//  AddMovieRouter.swift
//  MovieStoreCleanArchitecture
//
//  Created by Achraf TRABELSI on 17/09/2018.
//  Copyright (c) 2018 Achraf TRABELSI. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddMovieRoutingLogic {
    func popViewController(_ navigationController: UINavigationController)
}

protocol AddMovieDataPassing {
    var dataStore: AddMovieDataStore? { get }
}

class AddMovieRouter: NSObject, AddMovieRoutingLogic, AddMovieDataPassing {
    
    weak var viewController: AddMovieViewController?
    var dataStore: AddMovieDataStore?
    
    // MARK: Routing
    
    func popViewController(_ navigationController: UINavigationController) {
        navigationController.popViewController(animated: true)
    }
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: AddMovieViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: AddMovieDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
